/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarCard: typeof import('./src/components/CalendarCard.vue')['default']
    CalendarDays: typeof import('./src/components/CalendarDays.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MealPlanner: typeof import('./src/components/MealPlanner.vue')['default']
    RecipeList: typeof import('./src/components/RecipeList.vue')['default']
    RecipeTable: typeof import('./src/components/RecipeTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
